name: oumas_delicacy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # General Dependencies
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  path: ^1.8.3
  http: ^1.2.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  
  # UI/UX & Assets
  lottie: ^3.0.0
  badges: ^3.0.2
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.0.0
  like_button: ^2.0.5
  flutter_neumorphic: ^3.2.0
  concentric_transition: ^1.0.3

  # Auth & Services
  supabase_flutter: ^2.6.0
  sign_in_button: ^4.0.1
  flutter_dotenv: ^5.1.0

  # Map & Location
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  connectivity_plus: ^6.0.0
  
  # File Management
  image_picker: ^1.0.4
  file_picker: ^10.3.3
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  share_plus: ^12.0.0

  # Payment/PDF/Printing
  flutter_stripe: ^12.0.2
  printing: ^5.0.0
  pdf: ^3.11.3
  open_filex: ^4.7.0
  fl_chart: ^1.1.1

  # Native Configuration
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.3.5
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# --- Flutter Configuration ---
flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/images/splash_logo.png
    - assets/images/
    - .env.dev
    - .env.prod

# --- Tool Configuration ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  remove_alpha_android: true
  adaptive_icon_background: "#FFF3E0"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  ios: true