name: oumas_delicacy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_stripe: ^12.0.2
  intl: ^0.20.2
  lottie: ^3.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.2.3
  flutter_polyline_points: ^3.0.1
  image_picker: ^1.0.4
  file_picker: ^10.3.3   # âœ… upgraded to latest stable version
  path_provider: ^2.1.1
  provider: ^6.0.5
  path: ^1.8.3
  shared_preferences: ^2.1.1
  fl_chart: ^1.1.1
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  sign_in_button: ^4.0.1
  printing: ^5.0.0
  pdf: ^3.11.3
  open_filex: ^4.7.0
  badges: ^3.0.2
  share_plus: ^12.0.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/Chapati.jpg
    - assets/images/Githeri.jpg
    - assets/images/Ugali.jpg
    - assets/images/pilau.jpg
    - assets/images/ugali_nyama.jpg
    - assets/images/ugali_fish.jpg
    - assets/images/matoke.jpg
    - assets/images/samosa.jpg
    - assets/images/tea.jpg
    - assets/images/chips_beef.jpg
    - assets/images/burger.jpg
    - assets/images/kuku_ugali.jpg
    - assets/images/pilau_beef.jpg
    - assets/images/profile.jpg
    - assets/images/default.jpg
    - assets/images/app_icon.png
    - assets/images/bike.png
    - assets/images/dust.png
    - assets/images/food_pattern.png
    - assets/images/promo1.jpg
    - assets/images/promo2.jpg
    - assets/images/promo3.jpg
    - assets/animations/welcome.json
    - assets/animations/bike.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  # Optional extras (recommended):
  remove_alpha_ios: true
  remove_alpha_android: true

  # For adaptive icons (Android 8+):
  adaptive_icon_background: "#FFF3E0" 
  adaptive_icon_foreground: "assets/images/app_icon.png"