name: oumas_delicacy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_stripe: ^12.0.2
  intl: ^0.20.2
  lottie: ^3.0.0
  image_picker: ^1.0.4
  file_picker: ^10.3.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  path: ^1.8.3
  shared_preferences: ^2.1.1
  fl_chart: ^1.1.1
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  sign_in_button: ^4.0.1
  printing: ^5.0.0
  pdf: ^3.11.3
  open_filex: ^4.7.0
  badges: ^3.0.2
  share_plus: ^12.0.0
  change_app_package_name: ^1.5.0
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.0.0
  like_button: ^2.0.5
  flutter_neumorphic: ^3.2.0
  flutter_native_splash: ^2.3.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  url_launcher: ^6.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  remove_alpha_android: true
  adaptive_icon_background: "#FFF3E0"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#FFF3E0"
  image: assets/images/splash_logo.png
  color_dark: "#1A1A1A"
  image_dark: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#FFF3E0"
    image_dark: assets/images/splash_logo.png
    color_dark: "#1A1A1A"
  android: true
  ios: true